//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TQLangAE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TQLangAE.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Attributes.
        /// </summary>
        public static string AttributeGroupBoxName {
            get {
                return ResourceManager.GetString("AttributeGroupBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Points.
        /// </summary>
        public static string AttributeLabel {
            get {
                return ResourceManager.GetString("AttributeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} player changes found, press commit to save to updates..
        /// </summary>
        public static string ChangesDectected {
            get {
                return ResourceManager.GetString("ChangesDectected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tagCClass01=Theurgist
        ///tagCClass02=Wanderer
        ///tagCClass03=Rogue
        ///tagCClass04=Hunter
        ///tagCClass05=Stormcaller
        ///tagCClass06=Pyromancer
        ///tagCClass07=Defender
        ///tagCClass08=Warrior
        ///tagCClass09=Spellbreaker
        ///tagCClass10=Champion
        ///tagCClass11=Assassin
        ///tagCClass12=Slayer
        ///tagCClass13=Thane
        ///tagCClass14=Battlemage
        ///tagCClass15=Conqueror
        ///tagCClass16=Spellbinder
        ///tagCClass17=Guardian
        ///tagCClass18=Corsair
        ///tagCClass19=Warden
        ///tagCClass20=Paladin
        ///tagCClass21=Juggernaut
        ///tagCClass22=Conjurer
        ///tagCClass23=Summoner
        ///tag [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CharacterClass {
            get {
                return ResourceManager.GetString("CharacterClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentLevel=Level
        ///Class=Class
        ///CurrentXP=XP
        ///DifficultyUnlocked=Difficulty
        ///Money=Money
        ///SkillPoints=Skill Points
        ///AttributesPoints=Attribute Points
        ///BaseStrength=Base Str
        ///BaseDexterity=Base Dex
        ///BaseIntelligence=Base Int
        ///BaseHealth=Base Health
        ///BaseMana=Base Mana
        ///PlayTimeInSeconds=Time Played
        ///NumberOfDeaths=Deaths
        ///NumberOfKills=Kills
        ///ExperienceFromKills=XP From Kills
        ///HealthPotionsUsed=Health Pots Used
        ///ManaPotionsUsed=Mana Pots Used
        ///MaxLevel=Max Level
        ///NumHitsReceived=Hits Recv
        ///NumHitsInflicted= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CharacterInfoDisplay {
            get {
                return ResourceManager.GetString("CharacterInfoDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class.
        /// </summary>
        public static string ClassLabel {
            get {
                return ResourceManager.GetString("ClassLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dexterity.
        /// </summary>
        public static string DexterityLabel {
            get {
                return ResourceManager.GetString("DexterityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Difficulty0 {
            get {
                return ResourceManager.GetString("Difficulty0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Epic.
        /// </summary>
        public static string Difficulty1 {
            get {
                return ResourceManager.GetString("Difficulty1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legendary.
        /// </summary>
        public static string Difficulty2 {
            get {
                return ResourceManager.GetString("Difficulty2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diffculty.
        /// </summary>
        public static string DifficultyLabel {
            get {
                return ResourceManager.GetString("DifficultyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titan Quest Character Editor.
        /// </summary>
        public static string EditorProgramTitle {
            get {
                return ResourceManager.GetString("EditorProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string ExitMenuName {
            get {
                return ResourceManager.GetString("ExitMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenuName {
            get {
                return ResourceManager.GetString("FileMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string HealthLabel {
            get {
                return ResourceManager.GetString("HealthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligence.
        /// </summary>
        public static string IntelligenceLabel {
            get {
                return ResourceManager.GetString("IntelligenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leveling.
        /// </summary>
        public static string LevelGroupBoxName {
            get {
                return ResourceManager.GetString("LevelGroupBoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LevelLabel {
            get {
                return ResourceManager.GetString("LevelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mana.
        /// </summary>
        public static string ManaLabel {
            get {
                return ResourceManager.GetString("ManaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No changes found.
        /// </summary>
        public static string NoChangesDectected {
            get {
                return ResourceManager.GetString("NoChangesDectected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsMenuName {
            get {
                return ResourceManager.GetString("OptionsMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titan Quest Character Editor Settings.
        /// </summary>
        public static string OptionsMessage {
            get {
                return ResourceManager.GetString("OptionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A change to the configuration has been detected that requires a restart.  The application will now shutdown and restart..
        /// </summary>
        public static string RestartMessage {
            get {
                return ResourceManager.GetString("RestartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill Points.
        /// </summary>
        public static string SkillsLabel {
            get {
                return ResourceManager.GetString("SkillsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stength.
        /// </summary>
        public static string StrengthLabel {
            get {
                return ResourceManager.GetString("StrengthLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ValueLabel {
            get {
                return ResourceManager.GetString("ValueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP.
        /// </summary>
        public static string XPLabel {
            get {
                return ResourceManager.GetString("XPLabel", resourceCulture);
            }
        }
    }
}
